    - name: Create directory structure
      win_file:
        path: C:\nxlog\
        state: directory
    - name: Download NXLog
      win_get_url:
         url: https://nxlog.co/system/files/products/files/348/nxlog-ce-2.10.2150.msi
         dest: C:\NXLog\
    - name: Ensure nxlog installed
      win_package:
        path: C:\NXLog\nxlog-ce-2.10.2150.msi
    - name: Copy configuration for NXLog
      win_template:
         src: nxlog.conf.j2
         dest: 'C:\Program Files (x86)\nxlog\conf\nxlog.conf'
         notify: Restart NXLog
    - name: NXLog start
      win_service:
         name: nxlog
         state: started
         handlers:
    - name: nxlog restart
      win_service:
         name: nxlog
         state: restarted
